### ISSUE TITLE
Задание 4 (FizzBuzz 2)

### ISSUE THREAD

**Issue by shramko82** [puzankov/javascript_hw#3]
В условии неточность.
Вместо "исправить 1ю задачу..." нужно написать "исправить предыдущую задачу (FizzBuzz)".
Некоторые студенты путаются и переделывают задачу №1, там где нужно вводить число больше 100.

**Comment by puzankov** [comment]
я исправил
только вот ты не в том репозитории пишешь
тебе в online нужно писать

**Comment by shramko82** [comment]
Куда писать? )))
